image: node:16

pipelines:
  custom:
    deploy-to-staging:
      - step:
          name: Ready the Artifacts
          script:
            - apt-get update
            - apt-get install tar
            - tar czfv frontend.tar.gz frontend
            - tar czfv backend.tar.gz backend
          artifacts:
            - frontend.tar.gz
            - backend.tar.gz  
      - step:
          name: Deploying to Staging
          deployment: staging
          caches:
            - node
          script:
            - pipe: atlassian/heroku-deploy:2.0.0
              variables:
                HEROKU_API_KEY: $HEROKU_API_KEY
                HEROKU_APP_NAME: $HEROKU_APP_NAME_BACKEND
                ZIP_FILE: backend.tar.gz
            - pipe: atlassian/heroku-deploy:2.0.0
              variables:
                HEROKU_API_KEY: $HEROKU_API_KEY
                HEROKU_APP_NAME: $HEROKU_APP_NAME_FRONTEND
                ZIP_FILE: frontend.tar.gz